# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  connect_timeout: 10
  checkout_timeout: 10
  variables:
    statement_timeout: 20000
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('DB_THREADS') { 5 } %>

development:
  adapter: postgresql
  host: localhost
  database: amyandmartin_dev
  username: developer
  password: password
  port: 5432

test:
  <<: *default

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
